[tool.poetry]
name = "dvuploader"
version = "0.1.0"
description = "Python library for uploading (bulk) data to Dataverse"
authors = ["Jan Range"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core", "grequests", "joblib", "tqdm", "pydantic==1.10", "requests", "dotted_dict"]
build-backend = "poetry.core.masonry.api"
